spring:
  application:
    name: drogueria-bellavista

  jackson:
    serialization:
      write-dates-as-timestamps: false
    time-zone: America/Bogota

server:
  port: ${PORT:8080}
  servlet:
    context-path: /api

app:
  jwt:
    secret: ${APP_JWT_SECRET}
    expiration: 86400000